export const medicines = [
  { type: "Painkiller", level: 1, name: "Aertal", duration: "20m", packaging: "Pills", color: "blue" },
  { type: "Painkiller", level: 1, name: "Analgin", duration: "5m", packaging: "Pills", color: "green" },
  { type: "Painkiller", level: 1, name: "Ibuprofen", duration: "12m", packaging: "Pills", color: "white" },
  { type: "Painkiller", level: 1, name: "Movalis", duration: "15m", packaging: "Pills", color: "white" },
  { type: "Painkiller", level: 1, name: "Nise", duration: "20m", packaging: "Pills", color: "red" },
  { type: "Painkiller", level: 1, name: "Nimesil", duration: "21m", packaging: "Pills", color: "green" },
  { type: "Painkiller", level: 1, name: "Noopept", duration: "1m", packaging: "Pills", color: "blue" },
  { type: "Painkiller", level: 1, name: "Nurofen", duration: "13:30", packaging: "Pills", color: "red" },
  { type: "Painkiller", level: 1, name: "Pentalgin", duration: "20m", packaging: "Pills", color: "white" },
  { type: "Painkiller", level: 1, name: "Citramon", duration: "17m", packaging: "Pills", color: "green" },
  { type: "Painkiller", level: 2, name: "Irinex", duration: "15m", packaging: "Ampoules", color: "purple" },
  { type: "Painkiller", level: 2, name: "Hexobarbital", duration: "14m", packaging: "Ampoules", color: "white" },
  { type: "Painkiller", level: 3, name: "Ketamine", duration: "5m", packaging: "Ampoules", color: "purple" },
  { type: "Painkiller", level: 2, name: "Ketoprofen", duration: "30m", packaging: "Ampoules", color: "white" },
  { type: "Painkiller", level: 1, name: "Ketorol", duration: "20m", packaging: "Ampoules", color: "green" },
  { type: "Painkiller", level: 2, name: "Nimesulide", duration: "27m", packaging: "Ampoules", color: "orange" },
  { type: "Painkiller", level: 2, name: "Novocaine", duration: "25m", packaging: "Ampoules", color: "purple" },
  { type: "Painkiller", level: 2, name: "Propanidide", duration: "7m", packaging: "Ampoules", color: "orange" },
  { type: "Painkiller", level: 3, name: "Propofol", duration: "13m", packaging: "Ampoules", color: "orange" },
  { type: "Painkiller", level: 3, name: "Sodium oxybate", duration: "20m", packaging: "Ampoules", color: "white" },
  { type: "Painkiller", level: 3, name: "Thiopental", duration: "10m", packaging: "Ampoules", color: "red" },
  { type: "Painkiller", level: 1, name: "Ketorol", duration: "30m", packaging: "Injector", color: "green" },
  { type: "Painkiller", level: 2, name: "Promedol", duration: "30m", packaging: "Injector", color: "blue" },
  { type: "Poisoning", level: 1, name: "Carbopect", duration: "5m", packaging: "Pills", color: "white" },
  { type: "Poisoning", level: 1, name: "Mezim-forte", duration: "2m", packaging: "Pills", color: "red" },
  { type: "Poisoning", level: 1, name: "Mesalazine", duration: "6m", packaging: "Pills", color: "blue" },
  { type: "Poisoning", level: 1, name: "Nifuroxazide", duration: "5m", packaging: "Pills", color: "green" },
  { type: "Poisoning", level: 1, name: "Polysorb", duration: "5m", packaging: "Pills", color: "blue" },
  { type: "Poisoning", level: 1, name: "Salofalk", duration: "6m", packaging: "Pills", color: "red" },
  { type: "Poisoning", level: 1, name: "Coal", duration: "1m", packaging: "Pills", color: "black" },
  { type: "Poisoning", level: 1, name: "Ftalazol", duration: "5m", packaging: "Pills", color: "white" },
  { type: "Poisoning", level: 1, name: "Cerucal", duration: "2m", packaging: "Pills", color: "white" },
  { type: "Poisoning", level: 1, name: "Ercefuril", duration: "6:30", packaging: "Pills", color: "white" },
  { type: "Poisoning", level: 1, name: "Enterofuril", duration: "4m", packaging: "Pills", color: "red" },
  { type: "Poisoning", level: 2, name: "Heptral", duration: "20m", packaging: "Ampoules", color: "white" },
  { type: "Poisoning", level: 2, name: "Diclofenac", duration: "18m", packaging: "Ampoules", color: "white" },
  { type: "Poisoning", level: 2, name: "Ketorol", duration: "17m", packaging: "Ampoules", color: "green" },
  { type: "Poisoning", level: 2, name: "Metoclopramide", duration: "10m", packaging: "Ampoules", color: "orange" },
  { type: "Poisoning", level: 2, name: "Cerucal", duration: "13m", packaging: "Ampoules", color: "purple" },
  { type: "Poisoning", level: 2, name: "Ketorol", duration: "28m", packaging: "Injector", color: "green" },
  { type: "Antibiotics", level: 2, name: "Amoxiclav", duration: "20m", packaging: "Pills", color: "white" },
  { type: "Antibiotics", level: 2, name: "Amoxivan", duration: "10m", packaging: "Pills", color: "white" },
  { type: "Antibiotics", level: 1, name: "Amibactam", duration: "5m", packaging: "Pills", color: "white" },
  { type: "Antibiotics", level: 2, name: "Ampicillin", duration: "20m", packaging: "Pills", color: "blue" },
  { type: "Antibiotics", level: 2, name: "Ibuprofen", duration: "8m", packaging: "Pills", color: "white" },
  { type: "Antibiotics", level: 2, name: "Nurofen", duration: "10m", packaging: "Pills", color: "red" },
  { type: "Antibiotics", level: 1, name: "Paracetamol", duration: "4m", packaging: "Pills", color: "blue" },
  { type: "Antibiotics", level: 2, name: "Piperacillin", duration: "15m", packaging: "Pills", color: "green" },
  { type: "Antibiotics", level: 2, name: "Tetracycline", duration: "16m", packaging: "Pills", color: "red" },
  { type: "Antibiotics", level: 2, name: "Trichopolum", duration: "5m", packaging: "Pills", color: "green" },
  { type: "Antibiotics", level: 2, name: "Tsiprolet", duration: "9m", packaging: "Pills", color: "white" },
  { type: "Antibiotics", level: 2, name: "Grimipenem", duration: "15m", packaging: "Ampoules", color: "white" },
  { type: "Antibiotics", level: 2, name: "Ketorol", duration: "20m", packaging: "Ampoules", color: "green" },
  { type: "Antibiotics", level: 2, name: "Ceftriaxone", duration: "10m", packaging: "Ampoules", color: "purple" },
  { type: "Antibiotics", level: 2, name: "Cilaspen", duration: "10m", packaging: "Ampoules", color: "white" },
  { type: "Antibiotics", level: 2, name: "Erythromycin", duration: "15m", packaging: "Ampoules", color: "red" },
  { type: "Antibiotics", level: 2, name: "Ketorol", duration: "30m", packaging: "Injector", color: "green" },
  { type: "Sepsis", level: 3, name: "Amoxivan", duration: "22m", packaging: "Ampoules", color: "red" },
  { type: "Sepsis", level: 3, name: "Imipenem", duration: "20m", packaging: "Ampoules", color: "white" },
  { type: "Sepsis", level: 3, name: "Oxacilin", duration: "6m", packaging: "Ampoules", color: "purple" },
  { type: "Sepsis", level: 3, name: "Flemoklav", duration: "20m", packaging: "Ampoules", color: "orange" },
  { type: "Sepsis", level: 3, name: "Amoxivan", duration: "28m", packaging: "Injector", color: "blue" },
  { type: "Sepsis", level: 3, name: "Topoisomerase", duration: "30m", packaging: "Injector", color: "green" },
  { type: "Concussion", level: 0, name: "Actovegin", duration: "0", packaging: "Ampoules", color: "purple" },
  { type: "Concussion", level: 0, name: "Mexidol", duration: "0", packaging: "Ampoules", color: "green" },
  { type: "Concussion", level: 0, name: "Neurox", duration: "0", packaging: "Ampoules", color: "white" },
  { type: "Concussion", level: 1, name: "Noopept", duration: "1m", packaging: "Pills", color: "blue" },
  { type: "Concussion", level: 0, name: "Neurox", duration: "0", packaging: "Injector", color: "blue" },
  { type: "Hematomas", level: 0, name: "Viprosal", duration: "7m", packaging: "Salves", color: "white" },
  { type: "Hematomas", level: 0, name: "Kapsikam", duration: "6m", packaging: "Salves", color: "white" },
  { type: "Hematomas", level: 0, name: "Finalgon", duration: "10m", packaging: "Salves", color: "white" },
  { type: "Hematomas", level: 0, name: "Paclitaxel-Ebewe", duration: "15m", packaging: "Ampoules", color: "white" },
  { type: "Blood clotting", level: 0, name: "Vikasol", duration: "5m", packaging: "Pills", color: "white" },
  { type: "Blood clotting", level: 0, name: "Dicynon", duration: "4m", packaging: "Pills", color: "white" },
  { type: "Blood clotting", level: 0, name: "Sorbifer Durules", duration: "5m", packaging: "Pills", color: "white" },
  { type: "Blood clotting", level: 0, name: "Aminocaproic acid", duration: "10m", packaging: "Pills", color: "red" },
  { type: "Blood clotting", level: 0, name: "Vikasol", duration: "13m", packaging: "Ampoules", color: "purple" },
  { type: "Blood clotting", level: 0, name: "Nonacog Alpha", duration: "12m", packaging: "Ampoules", color: "white" },
  { type: "Blood clotting", level: 0, name: "Etamzilat", duration: "23m", packaging: "Ampoules", color: "orange" },
  { type: "Blood clotting", level: 0, name: "Erythropoietin", duration: "15m", packaging: "Injector", color: "red" },
  { type: "Blood Regeneration", level: 0, name: "Irovit", duration: "2:30", packaging: "Pills", color: "green" },
  { type: "Blood Regeneration", level: 0, name: "Sobifer Durules", duration: "5m", packaging: "Pills", color: "white" },
  { type: "Blood Regeneration", level: 0, name: "Tardyferon", duration: "3m", packaging: "Pills", color: "red" },
  { type: "Blood Regeneration", level: 0, name: "Heferol", duration: "4m", packaging: "Pills", color: "white" },
  { type: "Blood Regeneration", level: 0, name: "Maltofer", duration: "10m", packaging: "Ampoules", color: "white" },
  { type: "Blood Regeneration", level: 0, name: "Perftoran", duration: "5m", packaging: "Ampoules", color: "purple" },
  { type: "Blood Regeneration", level: 0, name: "Erythropoietin", duration: "15m", packaging: "Ampoules", color: "red" },
  { type: "Adrenalin", level: 1, name: "Adrenaline 0.5mg", duration: "15m", packaging: "Ampoules", color: "white" },
  { type: "Adrenalin", level: 2, name: "Adrenaline 1mg", duration: "10m", packaging: "Ampoules", color: "orange" },
  { type: "Adrenalin", level: 3, name: "Adrenaline 3mg", duration: "5m", packaging: "Ampoules", color: "red" },
  { type: "Adrenalin", level: 3, name: "Epinephrine", duration: "5m", packaging: "Injector", color: "blue" },
  { type: "Antidepressant", level: 1, name: "Agteminol", duration: "2m", packaging: "Pills", color: "white" },
  { type: "Antidepressant", level: 1, name: "Adepress", duration: "1m", packaging: "Pills", color: "white" },
  { type: "Antidepressant", level: 1, name: "Actaparoxetine", duration: "40sec", packaging: "Pills", color: "green" },
  { type: "Antidepressant", level: 1, name: "Amitriptyline", duration: "1:40", packaging: "Pills", color: "red" },
  { type: "Antidepressant", level: 1, name: "Venlafaxine", duration: "1:30", packaging: "Pills", color: "blue" },
  { type: "Antidepressant", level: 2, name: "Actaparoxetine", duration: "6:40", packaging: "Ampoules", color: "purple" },
  { type: "Antidepressant", level: 2, name: "Metralindol", duration: "5m", packaging: "Ampoules", color: "green" },
  { type: "Radiation", level: 1, name: "B-190", duration: "2m", packaging: "Pills", color: "blue" },
  { type: "Radiation", level: 1, name: "Potassium iron Hexocyan.", duration: "1:30", packaging: "Pills", color: "black" },
  { type: "Radiation", level: 1, name: "Potassium Iodide", duration: "1m", packaging: "Pills", color: "black" },
  { type: "Radiation", level: 2, name: "Mexamine", duration: "2m", packaging: "Pills", color: "green" },
  { type: "Radiation", level: 1, name: "Cystamine", duration: "2m", packaging: "Pills", color: "red" },
  { type: "Radiation", level: 2, name: "Carboxyme", duration: "5m", packaging: "Ampoules", color: "purple" },
  { type: "Radiation", level: 2, name: "Pentacin", duration: "5m", packaging: "Ampoules", color: "orange" },
  { type: "Radiation", level: 2, name: "Radio protector", duration: "7m", packaging: "Injector", color: "yellow" },
  { type: "Poison", level: 0, name: "Diazinon", duration: "0", packaging: "Ampoules", color: "green" },
  { type: "Poison", level: 0, name: "Dichlorvos", duration: "0", packaging: "Ampoules", color: "red" },
  { type: "Poison", level: 0, name: "Arsenic", duration: "0", packaging: "Ampoules", color: "green" },
  { type: "Poison", level: 0, name: "Cypermethrin", duration: "0", packaging: "Ampoules", color: "green" },
  { type: "Poison", level: 0, name: "Novichok", duration: "0", packaging: "Injector", color: "blue" },
];